Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/shared/*.rb"

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "**/*_spec.rb"

Style/NumericLiterals:
  Exclude:
    - "**/*_spec.rb"
