language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

before_install:
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - gem install rubocop

script:
  - rubocop
  - bundle exec rake
